### ISSUE TITLE
Berechtigung vom Admin

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_glp#10]
Gleiche Rechte auch in der Gruppe unterhalb.

**Comment by RetoBurri** [comment]
Sämtliche Administratoren Rechte(Rolle Administrator) müssen auf alle Ebenen unterhalb vererbt werden.

**Comment by RetoBurri** [comment]
- [ ] Der Kantonale Admin kann auf Ebenen unterhalb keine Abos erstellen, bearbeiten oder löschen

- [ ] Der Kantonale Admin kann auf Ebenen unterhalb keine Anlässe erstellen, bearbeiten oder löschen

**Comment by RetoBurri** [comment]
- [ ] Kantonaler Admin(Fiona Wiedemeier) kann Haupt Emailadressen von Personen, die auch auf nationaler Ebene eine Funktion haben (z.B. Nationalratskandidat) nicht mehr ändern.

**Comment by sampmueller** [comment]
Problem Filteransicht: kann keine Suche speichern, wenn ich nicht auf der Stufe direkt Admin bin.

**Comment by sampmueller** [comment]
Erfolgreich getestet, scheint nun alles wie gewünscht zu sein.

**Comment by olibrian** [comment]
Ergänzende Berechtigung hinzufügen:

- [ ]  Der Nationale Admin kann auf Ebenen unterhalb die Abonnenten (subscriptions) von Abos bearbeiten oder löschen
Beispiel im Kanton Bern: https://glp.puzzle.ch/de/groups/4/mailing_lists/56/subscriptions

Gibt es noch weitere Berechtigungen, welche der Kantonale Admin hat, welche vom Nationalen Admin nicht hat?

**Comment by kronn** [comment]
@olibrian 

An sich haben der nationale und der kantonale Admin volle Berechtigungen auf allen Gruppen der eigenen Ebene und allen darunter liegenden Ebenen.

Die folgenden Berechtigungen sind jedoch noch auf die eigene Ebene beschränkt:

- Kursanmeldungen anlegen und löschen
- API-Keys einer Gruppe auflisten und verwalten
- Zugriffsanfragen für eine Gruppe verwalten

Diese Berechtigungen sind meist an lokales Wissen gekoppelt, daher halte ich diese Einschränkungen vorerst für sinnvoll. Wie auch bei den bisherigen Anpassungen kann man aber auch hier eingreifen.

**Comment by sampmueller** [comment]
> @olibrian
> 
> An sich haben der nationale und der kantonale Admin volle Berechtigungen auf allen Gruppen der eigenen Ebene und allen darunter liegenden Ebenen.
> 
> Die folgenden Berechtigungen sind jedoch noch auf die eigene Ebene beschränkt:
> 
> * Kursanmeldungen anlegen und löschen
> * API-Keys einer Gruppe auflisten und verwalten
> * Zugriffsanfragen für eine Gruppe verwalten
> 
> Diese Berechtigungen sind meist an lokales Wissen gekoppelt, daher halte ich diese Einschränkungen vorerst für sinnvoll. Wie auch bei den bisherigen Anpassungen kann man aber auch hier eingreifen.

Ich bin nicht mehr zuständig, da ich aber beim Prozess dabei war, kommentiere ich dazu: Die Spezifikation war ganz klar: "**Sämtliche** Administratoren Rechte(Rolle Administrator) müssen auf alle Ebenen unterhalb vererbt werden" (fette Markierung von mir). Einwände von Seiten puzzle hätten früher kommuniziert werden sollen. Als nicht-Expert/innen des Systems können wir nicht sämtliche Administratoren-Rechte kennen und es wäre etwas viel verlangt gewesen, dass wir beim Testen alles merken. Und noch eine Frage: ist in der Formulierung "Kursanmeldungen anlegen und löschen
API-Keys einer Gruppe auflisten und verwalten
Zugriffsanfragen für eine Gruppe verwalten" auch das Bearbeiten der Abonnenten eines Abos enthalten?

**Comment by kronn** [comment]
Danke für den Hinweis auf diese Initialanforderung, diese war mir persönlich nicht bekannt, da ich später in das und nur temporär zum Projekt gekommen bin.

Das Bearbeiten der Abonennenten ist darin nicht mehr enthalten. Ich habe diese Aufstellung gemacht, nachdem ich dies angepasst haben. Die restliche Liste war sollte keine Absage sein, sondern nur die Antwort auf @olibrian s Frage. Ich habe das Issue hier bewusst nicht geschlossen, weil ich hier noch auf Feedback gewartet habe. 

Mit diesen Informatione werde ich auch die restliche Rechte anpassen, um dieser Spezifikation zu genügen.

**Comment by kronn** [comment]
Die andere Berechtigung sind jetzt auch so angepasst, dass ein Admin der nationalen auch auf der Ebene der Kantone alle Rechte  des dortigen Admins hat.

**Comment by olibrian** [comment]
Wird mit dem nächsten Release am 11.11 ausgerollt.
