### ISSUE TITLE
Nächtlicher Sync nach Mailchimp

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_glp#11]

**Comment by RetoBurri** [comment]
Hitobito muss die Mailinglisten jede Nacht um 00:30 Uhr mit MailChimp Synchronisieren, damit der manuelle Sync nicht mehr gemacht werden muss.

**Comment by carlobeltrame** [comment]
Eine Translation enthält noch den Text "Abonnenten können an die MailChimp-Liste exportiert werden, dies geschieht jedoch nicht automatisch. Diese Aktion überschreibt die MailChimp-Liste und bestehende Kontakte werden gelöscht."
Die sollte wohl noch angepasst werden.

**Comment by sampmueller** [comment]
Wir haben ein Abo zum Testen mit MailChimp synchronisiert (Aboverteiler Core-tester) und nun diverse Personen noch hinzugefügt. Wir warten nun ab, ob die neuen Abonnenten über den nächtlichen Sync erfolgreich zur Audience in MailChimp hinzugefügt werden.

**Comment by sampmueller** [comment]
Automatischer Sync hat im Test funktioniert.
