### ISSUE TITLE
Anpassungen Externe Formulare

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_glp#12]
- [ ] HTML Snippet soll jeweilige Umgebungen (`RAILS_HOST_NAME`) referenzieren 
- [ ] Versand an Administratoren soll via Checkbox auf der Person deaktivierbar sein (Feld `Eintrittsbenachrichtigung`.

**Comment by sampmueller** [comment]
Wir fanden beim Testen keine Option für das Abmelden von Notifikationsmails. Diese Änderung ist unentbehrlich für die Liveschaltung der Entwicklungen.

**Comment by olibrian** [comment]
Die Option ist direkt auf der Person via Checkbox einstellbar. In der Integrationsumgebung beispielsweise hier: https://glp.puzzle.ch/de/groups/1/people/25994/edit
![image](https://user-images.githubusercontent.com/9592347/85415142-401e1f00-b56d-11ea-820a-b098d80cc205.png)
Diese Checkbox ist nur auf Personen mit einer Administratoren Rolle sichtbar.

**Comment by CyrillSchelker** [comment]
Sam hat mich noch gebeten, diesen Punkt zu testen. Nach meiner Testreihe stimmt alles:
-Checkbox nur bei Admins vorhanden, nicht aber bei einfachen Mitgliedern und Sympathisanten.
-Nach herausnehmen des Häkchens erhält der Admin keine Eintrittsbenachrichtigungen mehr, getestet mit allen Formularen.
