### ISSUE TITLE
Export Spaltenauswahl ausblenden

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_glp#13]
Ausblenden vom Export:

Personenliste (https://glp.puzzle.ch/de/groups/1/people?returning=true ):
- [ ] Export -> CSV -> Spaltenauswahl
- [ ] Export -> Excel -> Spaltenauswahl

Abo (https://glp.puzzle.ch/de/groups/1/mailing_lists/6/subscriptions?returning=true): 
- [ ] Export -> CSV -> Spaltenauswahl
- [ ] Export -> Excel -> Spaltenauswahl

**Comment by sampmueller** [comment]
Spaltenauswahl erschien bei unserem Testen nicht mehr, somit in Ordnung. Durchaus wünschenswert, aber mit Anpassungen, die später erfolgen müssen. Somit würde ich dieses Issue nun schliessen.
