### ISSUE TITLE
Absender Adresse Anpassung entfernen

### ISSUE THREAD

**Issue by amaierhofer** [hitobito/hitobito_glp#19]
Aktuell ist nur der mxout nur für `glp-community.ch` im SPF konfiguriert, daher landen Emails von konfigurierten Absender `hitobito-glp@grunliberale.ch' oft im Spam. Es soll der default Absender verwendet werden.

**Comment by olibrian** [comment]
Was wird aktuell für ein Absender verwendet? Wird `nopreplay@glp-community.ch` verwendet? Falls ja, kann dieses Ticket geschlossen werden?

**Comment by olibrian** [comment]
Mails werden mit noreply@glp-community.ch verschickt. SPF passt somit.
