### ISSUE TITLE
Übersicht über abonnierte News-Abos

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_glp#2]
Übersicht über abonnierte News-Abos jeder Person

Fragen:
* nur solche, wo man sich selbständig An und Abmelden kann

Berechtigung:
* für eigenes Profil
* für Admins ersichtlich, sofern sie Adminrechte auf der Stufe der betreffenden Abos haben

**Comment by RetoBurri** [comment]
Welche sind «nur solche, für die man sich selbständig an- oder abmelden kann?

- [ ] Das ist in jedem Abo definiert, also gemäss Einstellung der Abos.

**Comment by olibrian** [comment]
Es werden nur Abos angezeigt, 
`Abonnenten dürfen sich selbst an-/abmelden`

**Comment by sampmueller** [comment]
Leider können wir dieses neue Feature nicht sehen. Sind in unserer Testumgebung bereits alle Entwicklungen auf dem aktuellsten Stand implementiert?

**Comment by sampmueller** [comment]
Jetzt sehen wir dieses Feature, es gibt allerdings noch Macken:
- Wieso sieht Hans-Ulrich Müller (einfaches Mitglied) das Abo glp Frauen Deutsch in seinem Profil unter Abos, obwohl er nicht dafür angemeldet ist?
- Vor allem einfache Mitglieder und Sympathisanten wie Hans-Ulrich Müller sollten ganz einfach alle Abos sehen können, für die sie sich an/abmelden können (z.B. einfacher Reiter). Im Moment ist diese Option sehr versteckt und quasi nicht brauchbar.
- Abos, für die man als einfaches Mitglied oder auch Admin keine Zugriffsrechte hat bzw. für die man sich auch nicht selbst an/abmelden kann, sollten am besten gar nicht angezeigt werden.
- Abonnierte Abos "Für Admins ersichtlich, sofern sie Adminrechte auf der Stufe der betreffenden Abos haben" -> wurde so umgesetzt, dass ich als Admin gleich **alle** Abos der Person sehe, sofern ich Zugriff auf die Person habe.

**Comment by olibrian** [comment]
Rückmeldung 
Pt1: bereits umgesetzt
Pt2: Option für eine spätere Umsetzung -> Neues Issue: 
Pt3: Nach Möglichkeit noch umsetzen. Aufwand klären.

**Comment by olibrian** [comment]
Nochmals zum Punkt3:
* Letzte Option "Entsprechende Schreibrechte habe" ist auf der Person nicht sinnvoll. Da je nach Person sehr viele Abos angezeigt werden. 
* Bei Abos wo sich der User an-/abmelden kann ein entsprechender Button anzeigen

Zur Ansicht:
* Eine Liste mit allen "Meine Abos" mit den Abos wo der User 
* Eine zweite Liste mit "Verfügbare Abos" wo sich er User anmelden kann

**Comment by sampmueller** [comment]
Scheint jetzt wie gewünscht zu funktionieren.
