### ISSUE TITLE
Debugging Sichtbarkeit von Spender Rollen

### ISSUE THREAD

**Issue by daniel-illi** [hitobito/hitobito_glp#44]
Extrahiert von #42 

Gemeldet von @sampmueller in https://github.com/hitobito/hitobito_glp/issues/42#issuecomment-1473611386

> Was ich allerdings beobachte: Ich sehe in der Spender:innengruppe bei den Spender:innen keine Rolle. Ich sollt das aber, oder?

![225877022-7a2ca6dc-04e1-4442-acca-c2705993e9f4](https://user-images.githubusercontent.com/636849/232512472-1ec7577b-310b-4c67-a255-a61af5c81bf7.png)

# TODO
- [x] Untersuchen, warum Sam in der Personenliste der Spendergruppen keine Spender-Rollen sieht. Das ist vermutlich wegen `visible_from_above: false` so, aber dann sollte er die Spender überhaupt nicht in dieser Gruppe aufgelistet sehen.

**Comment by sampmueller** [comment]
Hier mein Testbericht:
- Das Issue der nicht sichtbaren Rolle "Spender:in" besteht nach wie vor für Spendenverwalter:innen auf allen Ebenen. Anders wenn ich Spender:in bin und die Gruppe aufrufe, in der ich die Rolle habe, dann sehe ich mich selbst mit der Rolle Spender:in. Wenn ich auch die Berechtigung für die Gruppe habe, sehe ich die anderen Personen zwar in der Gruppe, aber nicht mit der Rolle.
- Die Rolle Spender:in wurde noch nicht in die anderen Sprachen übersetzt (FR, EN, IT). Wird das noch gemacht? Fehlen noch Übersetzungen auf Transifex?

**Comment by sampmueller** [comment]
Die Sichtbarkeit der Rolle "Spender:in" in der Gruppe ist in der Testinstanz weiterhin nicht gefixt, sehe ich das richtig? Bis wann wird das gefixt?

**Comment by sampmueller** [comment]
Spender:in-Rolle ist jetzt sichtbar in der Gruppe Spendergruppe auf allen Ebenen, diese Weiterentwicklung braucht somit aus meiner Sicht keine weiteren Anpassungen. Die fehlenden Übersetzungen habe ich auf Transifex eingetragen.
