### ISSUE TITLE
PLZ-Feld Formular GLP

### ISSUE THREAD

**Issue by mlue00** [hitobito/hitobito_glp#48]
Die GLP wünscht, dass bei den Anmeldeformularen für Mitglieder und Sympathisant:innen jeweils ausschliesslich vierstellige Postleitzahlen eingegeben werden können. Auch sollte sichergestellt werden, dass es sich bei den vier Stellen um Ziffern und keine anderen Zeichen handelt.
Es ist von folgenden Formularen die Rede, welche aus Hitobito stammen:
https://grunliberale.ch/mitmachen/mitglied-werden.html
https://grunliberale.ch/mitmachen/news-abonnieren.html

Im Zuge diese Issues sollte zudem der  PR #35 reverted und auf einen separaten Branch gepackt werden.
Hier sind noch einige Anpassungen notwendig, die aktuell aber keine Priorität haben. 
Somit sollten bei der GLP wieder problemlos Releases gemacht werden können.

# Tech-Spec

- PLZ-Feld auf 4 Ziffern limitieren
- genau 4 Ziffern, nicht mehr und nicht weniger
- nur Ziffern und keine anderen Zeichen
- PR #35 reverten
- Commits aus PR #35 auf Branch, damit diese verfügbar sind, wenn es mit der Umsetzung weiter geht

# ToDo

- [x] PLZ-Feld auf 4 Ziffern beschränkt
- [x] PR #35 reverted
- [x] Durchklicken
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

**Comment by sampmueller** [comment]
Wurde das noch nicht umgesetzt? 

Wir können auch 3 Ziffern eingeben und die Anmeldung landete im Ausland.
Auch Buchstaben und mehr als 4 Zeichen werden noch zugelassen.

**Comment by sampmueller** [comment]
Klappt alles m.E. Könntet Ihr die Meldung bei falschem Ausfüllen des PLZ-Feldes noch wie folgt anpassen? «Deine Eingabe muss mit dem geforderten Format übereinstimmen (Schweizer Postleitzahl mit vier Ziffern).»

**Comment by mlue00** [comment]
Bei der Eingabe der PLZ ist es nicht mehr ohne weiteres möglich das Formular im falschen Format abzuschicken. Entsprechend sollte die Meldung auch kaum mehr erscheinen. Die Meldung kommt aus dem Browser.
Wie besprochen, scheint die Anpassung nicht relevant genug zu sein.

**Comment by sampmueller** [comment]
Genau, vielen Dank!
