### ISSUE TITLE
Exportfunktion

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_glp#5]
Die Exportfunktion muss funktionieren und die Tags müssen auch exportiert werden

**Comment by amaierhofer** [comment]
Beim Personen Export mit "Allen Angaben" werden die Tags bereits exportiert.+

Wichtig ist, dass beim Einlesen nur Semicolon `;` nicht aber Komma `,` als Trennzeichen akzeptiert wird, da Rollen und Tags beispielsweise diese Komma verwenden um die die einzelnen Einträge zu trennen. 

@RetoBurri, was genau soll hier noch umgesetzt werden? Hast du eine Beispiel auf der Integrationsumgebung?

**Comment by fiwied** [comment]
In der Version von Hitobito, die wir verwenden, werden bei einem Export die Tags nicht mit exportiert. Wenn das bereits existiert müsste wahrscheinlich unsere hitobito-Version einfach aktualisiert werden. Ihr habt während unserem Meeting vor ein paar Wochen ja bereits so etwas angedeutet.

In jedem Fall wäre es aber nützlich, wenn die Tags beim Excel-Export nicht alle in einer Spalte sind (wie z.B. aktuell die Rollen), sondern pro "Tag-Kategorie" eine Spalte.

Liebe Grüsse Fiona (GS glp Kanton Zürich)

**Comment by danielnaef** [comment]
Ergänzend zu @fiwied : Es wäre super, wenn es die Export-Variante "Alle Angaben" auch bei den Abos gäbe ...

LG Daniel (GS glp Kanton Bern)

**Comment by sampmueller** [comment]
Allgemein formuliert: es ist ein wichtiges Kriterium, dass alle Exportfunktionen überall zur Verfügung stehen, also etwa im Abo wie auch in der Filteransicht. Wie Daniel schreibt, steht im Moment z.B. "Alle Angaben" nur für den Export über die Filteransicht zur Verfügung, nicht aber in einem Abo.

Allgemein wichtig ist ausserdem, dass der Export analog glp-NET funktioniert, dass man also die Angaben, die im Export erfasst und angezeigt werden sollen, selbst auswählen kann. 

Weiter braucht es unbedingt eine Anpassung der Rollen analog glp-NET. Im Moment werden die verschiedenen Rollen einer Person in einer Spalte in (soweit ich sehe) willkürlicher Reihenfolge angezeigt. Wichtig ist eine Aufteilung der Rollen und Ebenen, sodass ich z.B. alle Personen herausfiltern kann, die die Rolle Mitglied haben, egal auf welcher Stufe. In einer separaten Spalte sollte ich dann die Sektion sehen, in der die Personen die jeweilige Rolle besitzen, also z.B. Mitglied, Stäfa. Nur so können unsere Community-Manager die Daten brauchbar ordnen und nutzen. Kann man das vernünftig umsetzen?

**Comment by sampmueller** [comment]
Wenn wir im Abo oder in der Filteransicht Export: Spaltenauswahl wählen, können wir keine Spalten definieren für den Export. Sind in unserer Testumgebung bereits alle Entwicklungen auf dem aktuellsten Stand implementiert?

**Comment by olibrian** [comment]
Der Export "Spaltenauswahl" exportiert die aktuell in der Ansicht ausgewählten/dargestellten Spalten.

**Comment by sampmueller** [comment]
Die Spaltenauswahl ist für mich im Moment leider alles andere als schlüssig/funktional. Können wir das in einem Call zusammen anschauen?

**Comment by sampmueller** [comment]
- Unter Abo: Abonnenten: Export: Spalten ebenfalls konfigurieren
- Spaltenauswahl so konifigurieren, dass ich jeden Datenpunkt auswählen kann und dass nur die ausgewählten Spalten im Excel/CSV angezeigt werden, d.h. keine Pflichtspalten.

**Comment by olibrian** [comment]
Gemäss Besprechung und Mail werden die Spaltenexport im Moment ausgeblendet. Issue: https://github.com/hitobito/hitobito_glp/issues/13

**Comment by sampmueller** [comment]
Vorschlag: Issue 3 (Excel-Export) breiter auslegen (Issue 3: Exporte: Excel etc.) und dieses Issue schliessen.
