### ISSUE TITLE
Erweiterung Mailchimp Sync

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_glp#6]
Was fehlt:

- [ ] Anrede
- [ ] Sprache
- [ ] Tags
- [ ] Geschlecht

**Comment by RetoBurri** [comment]
Die oben erwähnten 4 Attribute müssen auch mit Mailchimp synchronisiert werden.

**Comment by amaierhofer** [comment]
@olibrian  @RetoBurri 

Leider unterstützt Mailchimp von den oben genannten Attributen nur `Sprache` und `Tags`. Das Feld `Geschlecht` können wir gut als Tag abbilden. Das Feld `Anrede` ist ein Freitext Feld, das eignet sich weniger als Tag. Wie wollen wir damit umgehen? Wie wichtig ist das Feld `Anrede`?

**Comment by RetoBurri** [comment]
Ich kläre das kurz mit der glp ab.

**Comment by RetoBurri** [comment]
Habe von der glp folgende Antwort erhalten: "Grundsätzlich ist es mir nicht wichtig, ob Anrede oder Geschlecht auf Mailchimp übertragen wird (einfach eines der beiden wäre super). Wichtig ist, dass es im Mailchimp nicht als Tag sondern als Spalte (analog wie z.B. der Name) eingelesen wird. Hier die Anleitung wie die Conditional Merge Tags im Mailchimp funktionieren: https://mailchimp.com/help/use-conditional-merge-tag-blocks/ und https://mailchimp.com/help/use-merge-tags-to-send-personalized-files/ 
Wenn ich das Geschlecht kenne, kann ich auch die Anrede einstellen. Ungefähr so:*|IF:GENDER = 0|* Lieber *|END:IF|*, *|IF:GENDER = 1|* Liebe *|END:IF|*. Darum wäre es gut, sicher das Geschlecht im Mailchimp zu haben. Die Anrede brauche ich nicht unbedingt."

@amaierhofer reicht Dir das so?

**Comment by amaierhofer** [comment]
Danke @RetoBurri  fürs Nachfrage, ich konnte auf Basis dieser Information die Implementierung abschliessen. Das Feature wird heute nacht auf Integration deployed.

**Comment by sampmueller** [comment]
Tags werden importiert, von Anrede/Geschlecht und Sprache sehen wir in MailChimp aber nichts.

**Comment by sampmueller** [comment]
Hier scheint alles i.O. zu sein: Tags, Sprache und Geschlecht werden importiert.
