### ISSUE TITLE
GLP Ausländische PLZ

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_glp#8]
PLZ werden nun akzeptiert, jedoch werden die Benutzer nirgends zugeordnet. Hier sollten Personen, die sich über das externe Formular anmelden und dabei eine PLZ mit mehr als 4 Ziffern benützen automatisch der Gruppe «Ausland/ étranger» zugeordnet werden.

- [ ] Bei Anmeldung mit PLZ mit mehr als 4 Ziffern soll die Person automatisch der Gruppe "Ausland" zugeordnet werden.

**Comment by amaierhofer** [comment]
Analog hitobito/hitobito_glp#1 mit folgenden Anpassungen

1) Falls zip_code mehr oder weniger als 4 Zeichen hat, automatische Zuweisung unterhalb der Auslands Gruppe 

Damit die Zuweisung zur Gruppe verlässlich klappt, ist es auf der Auslands Gruppe nicht mehr möglich einen *zip_code* festzulegen. Ich denke das ist auch nicht wünschenswert, da sätmliche Personen mit nicht 4 stelligen *zip_code* dort gesammelt werden sollten.

**Comment by sampmueller** [comment]
Funktioniert wie gewünscht.
