### ISSUE TITLE
Alle Mitglieder vom Kanton zeigen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_glp#9]
Entsprechender Filter

**Comment by RetoBurri** [comment]
Entsprechender Filter nicht mehr zu übersehen, Knopf = Link zur Ansicht aller Mitglieder/Hinweis/Erklärung überall.

**Comment by amaierhofer** [comment]
@RetoBurri  Folgende Fragen tauchen hier noch auf: 

**Wer genau ist ein Mitglied** Ich nehme an, es geht hier nur um die Rollen Mitglied aus den den Ebenen (Bund, Kanton, Bezirk, Ort) zugeordneten Gruppen. Ist das korrekt? 

**Auf Gruppe im Kanton** Soll der Filter nur Mitglieder aus der zugeordneten Gruppen im Kanton anzeigen oder alle Mitglieder aus Zugeordneten Gruppen darunter? (Bezirk, Ort).

**Auf Gruppe im Bezirk** Soll der Filter nur Mitglieder aus der zugeordneten Gruppen im Bezirk anzeigen oder alle Mitglieder aus Zugeordneten Gruppen darunter? (Ort), oder darüber (Kanton)

** Auf BundesEbene ** Ist hier angedacht einen eigen Filter zu haben, eventuell Alle Mitglieder aus zugeordneten Gruppen darunter (Kanton, Bezirk, Ort)

**Comment by fiwied** [comment]
Die Einschätzung der glp Kanton ZH zu deinen Fragen:

_- Wer genau ist ein Mitglied Ich nehme an, es geht hier nur um die Rollen Mitglied aus den den Ebenen (Bund, Kanton, Bezirk, Ort) zugeordneten Gruppen. Ist das korrekt?_
Im Moment werden, wenn ich auf Mitglieder und Sympathisanten glp Kanton Zürich klicke, alle Mitglieder und Sympis auf der kantonalen Ebene angezeigt. Idealerweise würden hier weiterhin alle **Mitglieder und Sympathisanten** angezeigt, aber eben auch von allen darunter liegenden Ebenen.

- _Auf Gruppe im Kanton Soll der Filter nur Mitglieder aus der zugeordneten Gruppen im Kanton anzeigen oder alle Mitglieder aus Zugeordneten Gruppen darunter? (Bezirk, Ort)._
Das ist genau das wichtige. Wenn ein kantonaler Administrator Hitobito öffnet und auf Mitglieder & Sympis klickt, sollen automatisch **alle Mitglieder auf der Ebene Kanton, Bezirk und Ort** angezeigt werden (nicht wie bis jetzt nur diejenigen auf der Ebene vom Kanton). 

_- Auf Gruppe im Bezirk Soll der Filter nur Mitglieder aus der zugeordneten Gruppen im Bezirk anzeigen oder alle Mitglieder aus Zugeordneten Gruppen darunter? (Ort), oder darüber (Kanton)_
Wenn ein Bezirks-Administrator Hitobito öffnet und auf Mitglieder & Sympis klickt, sollen automatisch **alle Mitglieder auf der Ebene Bezirk und Ort** angezeigt werden (nicht wie bis jetzt nur diejenigen auf der Ebene vom Bezirk). Die Mitglieder, welche nur auf der Ebene darüber gespeichert sind, sollen nicht angezeigt werden).

_- Auf jGLP Ebene und Ausland Ist hier ebenfalls ein analoger Filter angedacht?_
Wäre wohl sinnvoll. Aber da die jglp Schweiz als "Kanton" funktioniert im Hitobito und die Kantonssektionen als Bezirke, würde das wahrscheinlich gleich funktionieren. Das müsste keinen zusätzlichen Programmieraufwand bedeuten.

**Comment by danielnaef** [comment]
Aus meiner Sicht ist es nicht entscheidend, ob die Listen beim Seitenaufruf automatisch inkl. darunter liegenden Ebenen angezeigt werden (wie von @fiwied gewünscht) oder es einen gut sicht- und erkennbaren (!) Button dafür gibt (so habe ich @RetoBurri verstanden).

Es geht dabei immer nur um die betroffene + die darunter liegenden Ebenen. Ob dies auf Ebene Bund auch geht, ist eher eine technische Frage, da unter der nationalen Partei ja auch die jglp als "Kanton" erstellt ist. Die müsste bei der nationalen Liste dann wiederum ausgeschlossen werden.

**Wer genau ist ein Mitglied?** Schön wäre, wenn es diese Ansicht gibt für die Rolle Mitglied, für die Rolle Sympathisant und für beide Rollen zusammen.

**Comment by sampmueller** [comment]
Im Wesentlichen mit Fiona und Daniel einig. Ist jetzt natürlich eine Frage des technischen Aufwands. 

@RetoBurri Folgende Fragen tauchen hier noch auf:

Wer genau ist ein Mitglied Ich nehme an, es geht hier nur um die Rollen Mitglied aus den den Ebenen (Bund, Kanton, Bezirk, Ort) zugeordneten Gruppen. Ist das korrekt?

**Genau, das ist die Rolle "Mitglied" in der jeweiligen Gruppe Zugeordnete auf allen Stufen. Einfach zum Verständnis von der Parteistruktur her: es gibt die Rolle Mitglied technisch gesehen auf der Ebene Schweiz/Bund, diese sollte jedoch nicht wirklich verwendet werden. Auch Direktmitglieder der glp Schweiz werden dem jeweiligen Wohnkanton, wo es noch keine glp-Kantonalpartei gibt, zugeteilt, also z.B. Uri. Oder wenn sie im Ausland wohnen, werden sie der Sektion Ausland zugeteilt, die technisch gesehen auch ein Kanton ist.**

Auf BundesEbene Ist hier angedacht einen eigen Filter zu haben, eventuell Alle Mitglieder aus zugeordneten Gruppen darunter (Kanton, Bezirk, Ort)

**Ja, Bezirk und Ort sind aber viel wichtiger, auf Ebene Schweiz können wir ja gut mit den bestehenden Filterfunktionen umgehen.**

Auf jGLP Ebene und Ausland Ist hier ebenfalls ein analoger Filter angedacht?

**jglp wurde ja beantwortet und Ausland funktioniert genau gleich wie ein normaler Kanton, sollte also kein Zusatzaufwand sein. Im Gegenteil: eine Sonderregel für Ausland würde ja wohl mehr Aufwand geben.**

**Comment by carlobeltrame** [comment]
Hier lese ich teils widersprüchliche Angaben von verschiedenen Personen.

**Wer genau ist ein Mitglied?**
* @fiwied: Mitglieder und Sympathisanten
* @danielnaef: 3 separate Ansichten für Miglieder, Sympathisanten, und beide zusammen
* @sampmueller: Nur Mitglieder
* Aktuelle Implementation auf Integrationsumgebung https://glp.puzzle.ch: Nur Mitglieder

**Wie sieht der Filter auf Gruppen unterhalb des Kantons (Bezirk, Ort) aus?**
* @fiwied + @danielnaef: Nur Personen der betroffenen + der darunter liegenden Ebenen anzeigen
* Aktuelle Implementation: Filter verlinkt überall auf die Liste des ganzen Kantons

@fiwied @danielnaef @sampmueller die erste Frage müsste wohl intern in der GLP nochmals diskutiert werden.
@amaierhofer die zweite Frage ist auf Integration noch nicht korrekt implementiert.

**Comment by sampmueller** [comment]
> 
> 
> Hier lese ich teils widersprüchliche Angaben von verschiedenen Personen.
> 
> **Wer genau ist ein Mitglied?**
> 
>     * @fiwied: Mitglieder und Sympathisanten
> 
>     * @danielnaef: 3 separate Ansichten für Miglieder, Sympathisanten, und beide zusammen
> 
>     * @sampmueller: Nur Mitglieder
> 
>     * Aktuelle Implementation auf Integrationsumgebung https://glp.puzzle.ch: Nur Mitglieder
> 
> 
> **Wie sieht der Filter auf Gruppen unterhalb des Kantons (Bezirk, Ort) aus?**
> 
>     * @fiwied + @danielnaef: Nur Personen der betroffenen + der darunter liegenden Ebenen anzeigen
> 
>     * Aktuelle Implementation: Filter verlinkt überall auf die Liste des ganzen Kantons
> 
> 
> @fiwied @danielnaef @sampmueller die erste Frage müsste wohl intern in der GLP nochmals diskutiert werden.
> @amaierhofer die zweite Frage ist auf Integration noch nicht korrekt implementiert.

Ich glaube, Du hast unsere Antworten missverstanden, die bezogen sich z.T. nicht auf die Definition von Mitglied. Wenn wir von der glp von Mitgliedern sprechen, egal ob Fiona, Daniel oder ich, dann meinen wir damit immer Parteimitglieder im rechtlichen Sinn, keine Sympathisanten, diese Frage haben wir ja auch schon mit Andreas geklärt, meine ich. Für die Fitleransicht es wichtig, dass man die unterschiedlichen Rollen Mitglieder und Sympathisanten immer auseinanderhalten und getrennt betrachten und nach Status ordnen kann, auch wenn sie sich im Hitobito in der gleichen Gruppe befinden. Die Unterscheidung von Mitglied und Sympathisant/in ist für eine Partei ganz wwesentlich. Ist das somit geklärt oder bleibt dazu noch eine Frage?

Bzgl. Filter ist das von Fiona und Daniel Zitierte korrekt: **auf jeder Ebene werden die Personen der jeweiligen Ebene und aller darunterliegenden Ebenen** angezeigt. Von **darüberliegenden Ebenen** soll natürlich nichts angezeigt werden.

**Comment by carlobeltrame** [comment]
Danke für die Klarstellung, leider missverstehen wir uns immer noch. Ich glaube ich muss die Frage umformulieren die ich von Andreas übernommen habe. Zum Kontext: Ich versuche gerade, zu überprüfen, ob und wie weit die Anforderungen der GLP durch die Implementation von Andreas abgedeckt sind. Daher muss ich wissen (und das wird mir beim Lesen immer noch nicht klar):

**Welche Filter-Buttons bzw. Filter-Ansichten werden genau benötigt?** Also welche der folgenden Optionen sind gewünscht:
1. Ein Filter "Mitglieder im Kanton / Bezirk / Gruppe", der alle Personen mit der Rolle "Mitglied" auf dieser Ebene und darunter anzeigt
2. Ein Filter "Sympathisanten im Kanton / Bezirk / Gruppe", der alle Personen mit der Rolle "Sympathisant/-in" auf dieser Ebene und darunter anzeigt
3. Ein Filter "Ganzer Kanton / Bezirk / Gruppe", der alle Personen mit den Rollen "Mitglied" oder "Sympathisant/-in" auf dieser Ebene und darunter anzeigt

In meinem vormaligen Versuch die Kommentare zusammenzufassen war gemeint, Fiona möchte Option 3, Daniel möchte alle drei Optionen, und Samuel möchte Option 1.

**Comment by sampmueller** [comment]
Merci für die Antwort: es geht wie gesagt darum, dass man die beiden Rollen Mitglied und Sympathsant/in gut unterscheiden kann, aber auch die Übersicht über alles hat. Deshalb alle 3 Optionen, falls das nicht sehr viel aufwendiger ist als Option 1 (Option 2 allein wäre ja ohnehin sinnlos).

**Comment by sampmueller** [comment]
Funktioniert wie gewünscht.
